/**
 * PHARMACO-RUSH: Clinical Pharmacology & Trauma Triage Database
 * Real drug formulations, receptor mechanics, half-lives, and 15 clinical emergency cases.
 */

window.PHARMA_DATA = {
    receptors: {
        alpha1: { name: "α1 Adrenergic", location: "Vascular Smooth Muscle", effect: "Vasoconstriction → ↑ Systemic Vascular Resistance & ↑ MAP" },
        beta1: { name: "β1 Adrenergic", location: "Myocardium & SA Node", effect: "↑ Inotropy (Contractility) & ↑ Chronotropy (Heart Rate)" },
        beta2: { name: "β2 Adrenergic", location: "Bronchial Smooth Muscle", effect: "Bronchodilation & mild vasodilation" },
        gaba_a: { name: "GABA-A Receptor", location: "Central Nervous System", effect: "Chloride influx → Hyperpolarization & CNS Sedation/Anticonvulsant" },
        mu_opioid: { name: "μ-Opioid Receptor", location: "Brainstem & Spinal Cord", effect: "Analgesia, Respiratory Depression, Pupillary Constriction (Miosis)" },
        muscarinic: { name: "M2/M3 Muscarinic", location: "Heart, Lungs, Glands", effect: "Parasympathetic: ↓ HR, Bronchoconstriction, Secretions" },
        insulin_rec: { name: "Insulin Receptor", location: "Liver, Muscle, Adipose", effect: "GLUT4 translocation → Glucose & Potassium shift into cells" },
        v1_vasopressin: { name: "V1 Vasopressin", location: "Vascular Smooth Muscle", effect: "Potent non-adrenergic vasoconstriction" }
    },

    drugs: [
        // Resuscitation & Pressors
        {
            id: "epinephrine",
            name: "Epinephrine (Adrenaline)",
            category: "pressors",
            categoryName: "Resuscitation & Pressors",
            badge: "⚡ First-Line ACLS",
            unit: "mg",
            typicalDose: 1.0,
            doseMin: 0.1,
            doseMax: 3.0,
            step: 0.1,
            routes: ["IV Push", "IM Auto-Inject", "Infusion"],
            preferredRoute: "IV Push",
            halfLifeSec: 18,
            receptors: ["alpha1", "beta1", "beta2"],
            effects: { hr: +35, map: +30, spo2: +12, rhythm_support: true },
            indication: "Cardiac arrest (ACLS), severe Anaphylaxis, refractory Bradycardia.",
            contraindication: "Avoid unmonitored rapid push in normotensive conscious patients.",
            pearl: "Stimulates α1 (vasoconstriction), β1 (increased cardiac output), and β2 (bronchodilation in anaphylaxis)."
        },
        {
            id: "norepinephrine",
            name: "Norepinephrine (Levophed)",
            category: "pressors",
            categoryName: "Resuscitation & Pressors",
            badge: "🩸 Sepsis Pressor #1",
            unit: "mcg/min",
            typicalDose: 12,
            doseMin: 2,
            doseMax: 40,
            step: 2,
            routes: ["Continuous Infusion"],
            preferredRoute: "Continuous Infusion",
            halfLifeSec: 25,
            receptors: ["alpha1", "beta1"],
            effects: { hr: +8, map: +38, spo2: +2 },
            indication: "Septic shock, profound distributive hypotension, vasodilatory shock.",
            contraindication: "Hypovolemia without prior fluid volume resuscitation.",
            pearl: "'Levophed leaves 'em dead' is an old myth; it is the gold standard pressor to restore organ perfusion in distributive septic shock."
        },
        {
            id: "vasopressin",
            name: "Vasopressin (ADH)",
            category: "pressors",
            categoryName: "Resuscitation & Pressors",
            badge: "🧬 Non-Adrenergic Pressor",
            unit: "units/min",
            typicalDose: 0.03,
            doseMin: 0.01,
            doseMax: 0.08,
            step: 0.01,
            routes: ["Continuous Infusion"],
            preferredRoute: "Continuous Infusion",
            halfLifeSec: 35,
            receptors: ["v1_vasopressin"],
            effects: { hr: 0, map: +25, spo2: 0 },
            indication: "Refractory vasodilatory shock unresponsive to high-dose catecholamines.",
            contraindication: "Severe coronary artery ischemia.",
            pearl: "Bypasses desensitized adrenergic receptors by acting directly on V1 receptors in vascular smooth muscle."
        },
        {
            id: "atropine",
            name: "Atropine Sulfate",
            category: "cardiac",
            categoryName: "Cardiovascular & Rhythm",
            badge: "❤️ Anti-Muscarinic",
            unit: "mg",
            typicalDose: 1.0,
            doseMin: 0.5,
            doseMax: 3.0,
            step: 0.5,
            routes: ["IV Push"],
            preferredRoute: "IV Push",
            halfLifeSec: 30,
            receptors: ["muscarinic"],
            effects: { hr: +40, map: +12, secretions: -50 },
            indication: "Symptomatic sinus bradycardia, organophosphate/cholinergic poisoning.",
            contraindication: "Glaucoma, high-grade 2nd/3rd-degree AV blocks with wide QRS (requires pacing).",
            pearl: "Blocks vagal parasympathetic tone at the SA node. Minimum effective adult dose is 0.5mg (lower doses can paradoxically slow HR)."
        },
        {
            id: "amiodarone",
            name: "Amiodarone",
            category: "cardiac",
            categoryName: "Cardiovascular & Rhythm",
            badge: "🫀 Class III Antiarrhythmic",
            unit: "mg",
            typicalDose: 300,
            doseMin: 150,
            doseMax: 450,
            step: 150,
            routes: ["IV Push", "IV Infusion"],
            preferredRoute: "IV Push",
            halfLifeSec: 45,
            receptors: ["beta1"],
            effects: { hr: -20, stabilize_rhythm: true },
            indication: "Refractory Ventricular Fibrillation (V-Fib) and Pulseless V-Tach after defibrillation.",
            contraindication: "Severe sinus node dysfunction without pacemaker, prolonged QTc.",
            pearl: "Multichannel blocker (K+, Na+, Ca2+, beta). 300mg IV push in arrest, followed by 150mg repeat."
        },
        {
            id: "adenosine",
            name: "Adenosine",
            category: "cardiac",
            categoryName: "Cardiovascular & Rhythm",
            badge: "⏱️ AV Node Reset",
            unit: "mg",
            typicalDose: 6.0,
            doseMin: 6.0,
            doseMax: 12.0,
            step: 6.0,
            routes: ["Rapid IV Push"],
            preferredRoute: "Rapid IV Push",
            halfLifeSec: 8,
            receptors: ["muscarinic"],
            effects: { reset_svt: true, hr_temp_asystole: true },
            indication: "Stable Paroxysmal Supraventricular Tachycardia (SVT / PSVT).",
            contraindication: "Asthma/bronchospasm, 2nd or 3rd degree AV heart block.",
            pearl: "Ultra-short half-life (<10s). Must be administered via antecubital rapid push with immediate 20mL saline flush."
        },
        {
            id: "nitroglycerin",
            name: "Nitroglycerin (NTG)",
            category: "cardiac",
            categoryName: "Cardiovascular & Rhythm",
            badge: "🌊 Venodilator / Preload Reducer",
            unit: "mcg/min",
            typicalDose: 40,
            doseMin: 10,
            doseMax: 150,
            step: 10,
            routes: ["Continuous Infusion", "Sublingual"],
            preferredRoute: "Continuous Infusion",
            halfLifeSec: 20,
            receptors: [],
            effects: { map: -30, hr: +5, preload_reduction: true },
            indication: "Acute pulmonary edema, acute coronary syndrome / angina, hypertensive crisis.",
            contraindication: "Right ventricular myocardial infarction, phosphodiesterase-5 inhibitors (sildenafil) within 24h.",
            pearl: "Generates Nitric Oxide (NO) → cGMP activation → primarily venodilation, unloading overloaded left ventricles."
        },
        {
            id: "labetalol",
            name: "Labetalol",
            category: "cardiac",
            categoryName: "Cardiovascular & Rhythm",
            badge: "🛡️ Combined α1 & β-Blocker",
            unit: "mg",
            typicalDose: 20,
            doseMin: 10,
            doseMax: 80,
            step: 10,
            routes: ["Slow IV Push"],
            preferredRoute: "Slow IV Push",
            halfLifeSec: 40,
            receptors: ["alpha1", "beta1", "beta2"],
            effects: { map: -35, hr: -18 },
            indication: "Hypertensive emergency, aortic dissection, preeclampsia.",
            contraindication: "Severe bradycardia, cardiogenic shock, decompensated acute heart failure.",
            pearl: "Dual action: α1 blockade reduces peripheral resistance while β1 blockade prevents reflex tachycardia."
        },

        // Antidotes & Tox
        {
            id: "naloxone",
            name: "Naloxone (Narcan)",
            category: "antidotes",
            categoryName: "Antidotes & Toxicology",
            badge: "🚨 Opioid Antagonist",
            unit: "mg",
            typicalDose: 0.4,
            doseMin: 0.1,
            doseMax: 2.0,
            step: 0.1,
            routes: ["IV Push", "IN Intranasal", "IM Auto-Inject"],
            preferredRoute: "IV Push",
            halfLifeSec: 30,
            receptors: ["mu_opioid"],
            effects: { spo2: +25, rr: +14, opioid_reversal: true },
            indication: "Severe opioid toxicity with respiratory depression and miosis (pinpoint pupils).",
            contraindication: "None in severe respiratory arrest. Titrate in chronic opioid users to avoid acute withdrawal storm.",
            pearl: "Pure competitive antagonist at μ-opioid receptors. Half-life is shorter than many opioids (monitor for resedation!)."
        },
        {
            id: "flumazenil",
            name: "Flumazenil",
            category: "antidotes",
            categoryName: "Antidotes & Toxicology",
            badge: "🧬 Benzodiazepine Antagonist",
            unit: "mg",
            typicalDose: 0.2,
            doseMin: 0.1,
            doseMax: 1.0,
            step: 0.1,
            routes: ["Slow IV Push"],
            preferredRoute: "Slow IV Push",
            halfLifeSec: 25,
            receptors: ["gaba_a"],
            effects: { cns_arousal: true, rr: +8 },
            indication: "Pure procedural benzodiazepine overdose/sedation reversal.",
            contraindication: "Chronic benzodiazepine dependence or mixed tricyclic antidepressant overdose (triggers refractory seizures!).",
            pearl: "Competitive antagonist at the GABA-A benzodiazepine binding site."
        },
        {
            id: "calcium_gluconate",
            name: "Calcium Gluconate 10%",
            category: "antidotes",
            categoryName: "Antidotes & Toxicology",
            badge: "⚡ Cardiac Membrane Stabilizer",
            unit: "grams",
            typicalDose: 2.0,
            doseMin: 1.0,
            doseMax: 3.0,
            step: 1.0,
            routes: ["Slow IV Push"],
            preferredRoute: "Slow IV Push",
            halfLifeSec: 40,
            receptors: [],
            effects: { stabilize_myocardium: true, prevent_arrest: true },
            indication: "Hyperkalemia with ECG changes (peaked T-waves, widened QRS), hypocalcemia, calcium channel blocker overdose.",
            contraindication: "Digitalis/Digoxin toxicity (use caution).",
            pearl: "Does not lower serum potassium! It raises cardiac threshold potential, stabilizing the cardiomyocyte resting membrane against fatal ventricular arrhythmias."
        },
        {
            id: "sodium_bicarbonate",
            name: "Sodium Bicarbonate 8.4%",
            category: "antidotes",
            categoryName: "Antidotes & Toxicology",
            badge: "🧪 Alkalinizer & Fast-Na+ Restorer",
            unit: "mEq",
            typicalDose: 50,
            doseMin: 50,
            doseMax: 150,
            step: 50,
            routes: ["IV Push"],
            preferredRoute: "IV Push",
            halfLifeSec: 35,
            receptors: [],
            effects: { narrow_qrs: true, ph_boost: +0.15 },
            indication: "Tricyclic Antidepressant (TCA) toxicity with QRS widening > 100ms, severe metabolic acidosis, sodium channel blocker poisonings.",
            contraindication: "Metabolic/respiratory alkalosis, hypocalcemia.",
            pearl: "Alkalinizes serum pH (unbinding TCAs from Na+ channels) and flooding fast sodium channels with Na+ ions."
        },
        {
            id: "pralidoxime",
            name: "Pralidoxime (2-PAM)",
            category: "antidotes",
            categoryName: "Antidotes & Toxicology",
            badge: "🛡️ Acetylcholinesterase Reactivator",
            unit: "grams",
            typicalDose: 1.5,
            doseMin: 1.0,
            doseMax: 2.0,
            step: 0.5,
            routes: ["Slow IV Infusion"],
            preferredRoute: "Slow IV Infusion",
            halfLifeSec: 45,
            receptors: ["muscarinic"],
            effects: { undo_cholinergic: true, muscle_strength: +30 },
            indication: "Organophosphate insecticide or nerve agent poisoning (DUMBELS toxidrome) combined with Atropine.",
            contraindication: "Carbamate toxicity (use atropine alone).",
            pearl: "Reactivates phosphorylated acetylcholinesterase before irreversible 'aging' occurs, restoring nicotinic and muscarinic neuromuscular function."
        },

        // Metabolic & Fluids
        {
            id: "dextrose_50",
            name: "Dextrose 50% (D50W)",
            category: "metabolic",
            categoryName: "Metabolic & Fluids",
            badge: "🍬 Rapid Glycemic Rescue",
            unit: "mL (25g)",
            typicalDose: 50,
            doseMin: 25,
            doseMax: 100,
            step: 25,
            routes: ["Slow IV Push"],
            preferredRoute: "Slow IV Push",
            halfLifeSec: 30,
            receptors: [],
            effects: { glucose: +120, cns_arousal: true },
            indication: "Severe symptomatic hypoglycemia (Blood Glucose < 60 mg/dL), altered mental status.",
            contraindication: "Hyperglycemia, intracranial hemorrhage without documented hypoglycemia.",
            pearl: "Provides 25 grams of pure hypertonic glucose. Re-check capillary blood glucose within 15 minutes."
        },
        {
            id: "insulin_regular",
            name: "Insulin Regular (Humulin R)",
            category: "metabolic",
            categoryName: "Metabolic & Fluids",
            badge: "🧬 Glucose & K+ Translocator",
            unit: "Units",
            typicalDose: 10,
            doseMin: 5,
            doseMax: 20,
            step: 5,
            routes: ["IV Push", "Continuous Infusion"],
            preferredRoute: "IV Push",
            halfLifeSec: 35,
            receptors: ["insulin_rec"],
            effects: { glucose: -100, potassium_shift: -1.2 },
            indication: "Diabetic Ketoacidosis (DKA), Hyperglycemic Hyperosmolar State (HHS), severe Hyperkalemia (given with Dextrose).",
            contraindication: "Hypoglycemia (unless co-administered with D50 for hyperkalemia), hypokalemia (K+ < 3.3).",
            pearl: "Shifts potassium into cells via Na+/K+ ATPase pump activation. In hyperkalemia, MUST be given with D50 to prevent fatal hypoglycemia."
        },
        {
            id: "normal_saline",
            name: "0.9% Normal Saline Bolus",
            category: "metabolic",
            categoryName: "Metabolic & Fluids",
            badge: "💧 Crystalloid Resuscitation",
            unit: "mL",
            typicalDose: 1000,
            doseMin: 500,
            doseMax: 2500,
            step: 500,
            routes: ["Rapid IV Pressure Bag"],
            preferredRoute: "Rapid IV Pressure Bag",
            halfLifeSec: 50,
            receptors: [],
            effects: { map: +18, hr: -12, preload_boost: true },
            indication: "Hypovolemic shock, dehydration, fluid-refractory hypotension in sepsis (30 mL/kg guideline).",
            contraindication: "Acute decompensated pulmonary edema / fluid overload.",
            pearl: "Isotonic crystalloid expands intravascular volume, increasing venous return (preload) and stroke volume."
        },

        // Sedation & Analgesia
        {
            id: "fentanyl",
            name: "Fentanyl Citrate",
            category: "sedation",
            categoryName: "Analgesia & Sedation",
            badge: "💉 Potent μ-Opioid Analgesic",
            unit: "mcg",
            typicalDose: 50,
            doseMin: 25,
            doseMax: 150,
            step: 25,
            routes: ["Slow IV Push"],
            preferredRoute: "Slow IV Push",
            halfLifeSec: 30,
            receptors: ["mu_opioid"],
            effects: { pain: -80, hr: -8, rr: -6, map: -5 },
            indication: "Severe trauma pain, rapid sequence intubation analgesia, acute coronary syndrome.",
            contraindication: "Severe respiratory depression without airway control.",
            pearl: "100x more potent than morphine with minimal histamine release (less hypotension than morphine)."
        },
        {
            id: "propofol",
            name: "Propofol (Diprivan)",
            category: "sedation",
            categoryName: "Analgesia & Sedation",
            badge: "😴 GABA-A Hypnotic",
            unit: "mg",
            typicalDose: 100,
            doseMin: 40,
            doseMax: 200,
            step: 20,
            routes: ["IV Push", "Continuous Infusion"],
            preferredRoute: "IV Push",
            halfLifeSec: 20,
            receptors: ["gaba_a"],
            effects: { sedation: +100, map: -22, hr: -10, rr: -12 },
            indication: "General anesthesia induction, procedural sedation for cardioversion, ICU mechanical ventilation sedation.",
            contraindication: "Egg/soy severe anaphylaxis, hypotension with unresuscitated shock.",
            pearl: "Rapid onset and offset due to redistribution. Strong peripheral vasodilation may drop blood pressure."
        },

        // Interventions (Electricity / Airway)
        {
            id: "defibrillation",
            name: "Biphasic Defibrillator Shock",
            category: "electrical",
            categoryName: "Electrical / Interventions",
            badge: "⚡ 200J Biphasic Shock",
            unit: "Joules",
            typicalDose: 200,
            doseMin: 120,
            doseMax: 360,
            step: 40,
            routes: ["Anterolateral Pads"],
            preferredRoute: "Anterolateral Pads",
            halfLifeSec: 1,
            receptors: [],
            effects: { electrical_reset: true },
            indication: "SHOCKABLE RHYTHMS ONLY: Ventricular Fibrillation (V-Fib) and Pulseless Ventricular Tachycardia (pVT).",
            contraindication: "NON-SHOCKABLE RHYTHMS: Asystole, PEA (Pulseless Electrical Activity), Sinus Rhythm with pulse.",
            pearl: "Depolarizes the entire myocardium simultaneously, allowing the natural pacemaker (SA Node) to regain control."
        },
        {
            id: "synchronized_cardioversion",
            name: "Synchronized Cardioversion",
            category: "electrical",
            categoryName: "Electrical / Interventions",
            badge: "🫀 R-Wave Synced Shock",
            unit: "Joules",
            typicalDose: 100,
            doseMin: 50,
            doseMax: 200,
            step: 50,
            routes: ["Sync Pads Mode"],
            preferredRoute: "Sync Pads Mode",
            halfLifeSec: 1,
            receptors: [],
            effects: { sync_reset: true },
            indication: "Unstable Supraventricular Tachycardia (SVT), Rapid Atrial Fibrillation, or Unstable Monomorphic VT with a pulse.",
            contraindication: "Ventricular Fibrillation (cannot synchronize to an R-wave!).",
            pearl: "Times electrical delivery precisely to the R-wave of the QRS complex to avoid firing on the T-wave ('R-on-T' induced V-Fib)."
        }
    ],

    // 15 Structured Campaign Cases
    cases: [
        {
            id: 1,
            title: "Peanut Dust Collapse",
            badge: "CASE #01 // ANAPHYLAXIS",
            difficulty: "Rookie EMT",
            patient: {
                name: "Marcus V., Age 24",
                presentation: "Collapses in a bakery 10 minutes after eating a pastry. Stridor, diffuse urticaria (hives), facial angioedema, labored breathing.",
                vitals: { hr: 138, sbp: 72, dbp: 40, spo2: 82, glucose: 105, rr: 28, temp: 37.1 },
                rhythm: "sinus_tachycardia",
                rhythmName: "Sinus Tachycardia (138 bpm)",
                pupils: "Normal (3mm)",
                lungs: "Severe expiratory wheezing & stridor",
                toxidrome: "IgE-Mediated Massive Histamine Release & Bronchospasm"
            },
            correctDrugs: ["epinephrine", "normal_saline"],
            lethalMistakes: ["labetalol", "propofol", "adenosine"],
            targetVitals: { sbpMin: 95, spo2Min: 92, hrMax: 120 },
            debrief: "First-line therapy for anaphylaxis is Epinephrine intramuscularly/IV immediately! It activates α1 to reverse vasodilatory shock, β1 to restore cardiac output, and β2 to relax constricted bronchioles. Crystalloid bolus restores depleted intravascular volume."
        },
        {
            id: 2,
            title: "Alleyway Stupor",
            badge: "CASE #02 // TOXICOLOGY",
            difficulty: "Rookie EMT",
            patient: {
                name: "Unknown Male, Approx Age 30",
                presentation: "Found unresponsive in an alleyway with blue lips and agonal, shallow respirations at 4 breaths/min. Track marks on forearm.",
                vitals: { hr: 48, sbp: 88, dbp: 54, spo2: 68, glucose: 94, rr: 4, temp: 35.8 },
                rhythm: "sinus_bradycardia",
                rhythmName: "Sinus Bradycardia (48 bpm)",
                pupils: "Pinpoint Miosis (1mm)",
                lungs: "Severely hypoventilating, shallow",
                toxidrome: "Classic Opioid Toxidrome (Miosis + Respiratory Depression + CNS Depression)"
            },
            correctDrugs: ["naloxone"],
            lethalMistakes: ["fentanyl", "propofol", "labetalol"],
            targetVitals: { spo2Min: 94, rrMin: 12, hrMin: 60 },
            debrief: "Naloxone binds competitively to μ-opioid receptors, rapidly displacing the agonist and reversing fatal respiratory depression in seconds. Always monitor for rebound toxicity as naloxone's half-life is often shorter than the opioid."
        },
        {
            id: 3,
            title: "The Sudden Racing Heart",
            badge: "CASE #03 // CARDIOLOGY",
            difficulty: "Junior Resident",
            patient: {
                name: "Elena R., Age 32",
                presentation: "Sudden onset palpitation, chest tightness, and lightheadedness after 4 cups of espresso. Normal ECG prior to episode.",
                vitals: { hr: 215, sbp: 90, dbp: 60, spo2: 96, glucose: 110, rr: 22, temp: 36.9 },
                rhythm: "svt",
                rhythmName: "Paroxysmal Supraventricular Tachycardia (215 bpm)",
                pupils: "Normal (3mm)",
                lungs: "Clear bilaterally",
                toxidrome: "AV Nodal Reentry (PSVT)"
            },
            correctDrugs: ["adenosine"],
            lethalMistakes: ["epinephrine", "norepinephrine", "calcium_gluconate"],
            targetVitals: { hrMin: 65, hrMax: 100, sbpMin: 100 },
            debrief: "Adenosine produces profound transient AV-nodal blockade (half-life <10s) to interrupt the reentry circuit. Patient experiences brief transient asystole ('heart reset') followed by conversion to normal sinus rhythm."
        },
        {
            id: 4,
            title: "The Silent Diaphoresis",
            badge: "CASE #04 // METABOLIC",
            difficulty: "Junior Resident",
            patient: {
                name: "Arthur K., Age 68",
                presentation: "Type 1 diabetic found sweaty, trembling, and combative by family after taking morning insulin but skipping breakfast.",
                vitals: { hr: 124, sbp: 142, dbp: 86, spo2: 98, glucose: 24, rr: 20, temp: 36.6 },
                rhythm: "sinus_tachycardia",
                rhythmName: "Sinus Tachycardia (124 bpm)",
                pupils: "Dilated (5mm), diaphoretic skin",
                lungs: "Clear",
                toxidrome: "Neuroglycopenia & Sympathetic Surge"
            },
            correctDrugs: ["dextrose_50"],
            lethalMistakes: ["insulin_regular", "labetalol", "propofol"],
            targetVitals: { glucoseMin: 80, glucoseMax: 180, hrMax: 100 },
            debrief: "Severe neuroglycopenia (<60 mg/dL) requires immediate IV Dextrose 50% (D50W). Giving insulin in this state would be fatal!"
        },
        {
            id: 5,
            title: "The Wide-Complex Chaos",
            badge: "CASE #05 // ACLS RESUSCITATION",
            difficulty: "Senior Registrar",
            patient: {
                name: "David T., Age 59",
                presentation: "Complaining of crushing retrosternal chest pain, suddenly collapses. Monitored rhythm deteriorates into coarse chaotic fibrillatory waves. No carotid pulse.",
                vitals: { hr: 0, sbp: 0, dbp: 0, spo2: 45, glucose: 120, rr: 0, temp: 36.5 },
                rhythm: "vfib",
                rhythmName: "Coarse Ventricular Fibrillation (Shockable Arrest)",
                pupils: "Sluggish (4mm)",
                lungs: "Apneic",
                toxidrome: "Pulseless Cardiac Arrest (V-Fib)"
            },
            correctDrugs: ["defibrillation", "epinephrine", "amiodarone"],
            lethalMistakes: ["adenosine", "atropine", "labetalol"],
            targetVitals: { sbpMin: 85, hrMin: 50, hrMax: 130 },
            debrief: "V-Fib is a shockable rhythm! Immediate unsynchronized 200J biphasic defibrillation is paramount, accompanied by Epinephrine 1mg IV every 3-5 min and Amiodarone 300mg IV for refractory arrhythmias."
        },
        {
            id: 6,
            title: "Agricultural Mist",
            badge: "CASE #06 // TOXICOLOGY",
            difficulty: "Senior Registrar",
            patient: {
                name: "Carlos M., Age 44",
                presentation: "Pesticide crop-duster worker brought in drenched in sweat, vomiting, incontinent, with extreme salivation, wheezing, and pinpoint pupils.",
                vitals: { hr: 36, sbp: 80, dbp: 48, spo2: 74, glucose: 102, rr: 26, temp: 36.8 },
                rhythm: "sinus_bradycardia",
                rhythmName: "Severe Sinus Bradycardia (36 bpm)",
                pupils: "Pinpoint Miosis (1mm)",
                lungs: "Diffuse rhonchi & heavy bronchorrhea",
                toxidrome: "Cholinergic Crisis (SLUDGEM / DUMBELS)"
            },
            correctDrugs: ["atropine", "pralidoxime"],
            lethalMistakes: ["labetalol", "fentanyl", "propofol"],
            targetVitals: { hrMin: 65, spo2Min: 90, sbpMin: 95 },
            debrief: "Organophosphate poisoning irreversibly inhibits acetylcholinesterase, causing acetylcholine overload. High-dose Atropine competitively blocks muscarinic excess (clearing bronchial secretions), while Pralidoxime (2-PAM) regenerates the enzyme."
        },
        {
            id: 7,
            title: "The Peaked T-Wave Enigma",
            badge: "CASE #07 // RENAL & ELECTROLYTES",
            difficulty: "Senior Registrar",
            patient: {
                name: "Fatima B., Age 62",
                presentation: "End-Stage Renal Disease patient who missed 3 hemodialysis sessions. Generalized weakness, nausea. Telemetry shows tall, tented, symmetrical T-waves and widening QRS.",
                vitals: { hr: 52, sbp: 92, dbp: 56, spo2: 95, glucose: 135, rr: 18, temp: 36.7 },
                rhythm: "hyperkalemia_peaked",
                rhythmName: "Hyperkalemia with Peaked T-Waves (K+ = 7.9 mEq/L)",
                pupils: "Normal (3mm)",
                lungs: "Clear",
                toxidrome: "Severe Hyperkalemic Cardiotoxicity"
            },
            correctDrugs: ["calcium_gluconate", "insulin_regular", "dextrose_50"],
            lethalMistakes: ["labetalol", "amiodarone"],
            targetVitals: { hrMin: 60, sbpMin: 100 },
            debrief: "Hyperkalemic emergency requires a 3-step attack: 1) Calcium Gluconate to stabilize the cardiac membrane immediately, 2) Insulin Regular (with D50W to protect glucose) to drive K+ back into intracellular compartments."
        },
        {
            id: 8,
            title: "The Septic Abyss",
            badge: "CASE #08 // CRITICAL CARE",
            difficulty: "Fellow / Chief Resident",
            patient: {
                name: "Evelyn H., Age 77",
                presentation: "Urosepsis with altered mental status, fever, warm flushed extremities, and profound hypotension refractory to initial 500mL fluid challenge.",
                vitals: { hr: 128, sbp: 64, dbp: 32, spo2: 91, glucose: 148, rr: 26, temp: 39.4 },
                rhythm: "sinus_tachycardia",
                rhythmName: "Sinus Tachycardia (128 bpm)",
                pupils: "Sluggish (3.5mm)",
                lungs: "Bilateral coarse crackles at bases",
                toxidrome: "Distributive Septic Shock (MAP = 42 mmHg)"
            },
            correctDrugs: ["normal_saline", "norepinephrine"],
            lethalMistakes: ["labetalol", "nitroglycerin", "propofol"],
            targetVitals: { sbpMin: 95, hrMax: 110, spo2Min: 93 },
            debrief: "In distributive septic shock, severe systemic vasodilation collapses MAP. Norepinephrine is the first-line vasopressor to restore vascular tone and vital organ perfusion alongside crystalloid boluses."
        },
        {
            id: 9,
            title: "The Aortic Tear Pressure Cooker",
            badge: "CASE #09 // VASCULAR SURGICAL",
            difficulty: "Fellow / Chief Resident",
            patient: {
                name: "Viktor S., Age 55",
                presentation: "Tearing interscapular back pain radiating down chest. Bedside echo reveals Stanford Type A aortic dissection flap. Blood pressure is catastrophically elevated.",
                vitals: { hr: 110, sbp: 228, dbp: 130, spo2: 97, glucose: 115, rr: 20, temp: 37.0 },
                rhythm: "sinus_tachycardia",
                rhythmName: "Sinus Tachycardia with Hypertensive Crisis",
                pupils: "Reactive (3mm)",
                lungs: "Clear",
                toxidrome: "Aortic Dissection Shear Stress Crisis"
            },
            correctDrugs: ["labetalol", "nitroglycerin"],
            lethalMistakes: ["epinephrine", "norepinephrine", "atropine", "dextrose_50"],
            targetVitals: { sbpMin: 100, sbpMax: 120, hrMax: 65 },
            debrief: "Aortic dissection requires immediate anti-impulse therapy: beta-blockade with Labetalol first to reduce dP/dt (shear stress) and HR < 60, followed by vasodilators to target SBP between 100-120 mmHg."
        },
        {
            id: 10,
            title: "The Tricyclic Storm",
            badge: "CASE #10 // TOXICOLOGY",
            difficulty: "Fellow / Chief Resident",
            patient: {
                name: "Amber L., Age 27",
                presentation: "Intentional ingestion of 40 Amitriptyline tablets. Somnolent, dry mouth, flushed skin, QRS complex progressively widening to 160ms with right-axis deviation on ECG.",
                vitals: { hr: 132, sbp: 78, dbp: 44, spo2: 93, glucose: 98, rr: 12, temp: 38.2 },
                rhythm: "tca_wide_complex",
                rhythmName: "Wide-Complex Tachycardia (QRS = 164ms)",
                pupils: "Mydriasis (6mm)",
                lungs: "Clear",
                toxidrome: "Tricyclic Antidepressant (Fast Na+ Channel Blockade)"
            },
            correctDrugs: ["sodium_bicarbonate", "normal_saline"],
            lethalMistakes: ["amiodarone", "labetalol", "propofol"],
            targetVitals: { sbpMin: 95, hrMax: 110 },
            debrief: "TCA toxicity blocks fast sodium channels, widening the QRS and risking lethal torsades/ventricular arrhythmias. Hypertonic Sodium Bicarbonate (8.4%) alkalines serum pH to unbind the drug and floods channels with Na+ ions."
        },
        {
            id: 11,
            title: "Flash Pulmonary Drowning",
            badge: "CASE #11 // CARDIOPULMONARY",
            difficulty: "Attending Consultant",
            patient: {
                name: "George P., Age 73",
                presentation: "Wakes up gasping for air, orthopneic, coughing pink frothy sputum. History of ischemic heart failure. Extreme hypertension with wet bilateral crackles up to apex.",
                vitals: { hr: 126, sbp: 210, dbp: 118, spo2: 78, glucose: 130, rr: 34, temp: 36.9 },
                rhythm: "sinus_tachycardia",
                rhythmName: "Sinus Tachycardia (126 bpm)",
                pupils: "Normal (3mm)",
                lungs: "Severe bilateral pulmonary crackles & pink sputum",
                toxidrome: "Acute Sympathetic Flash Pulmonary Edema"
            },
            correctDrugs: ["nitroglycerin", "labetalol"],
            lethalMistakes: ["normal_saline", "epinephrine", "norepinephrine"],
            targetVitals: { sbpMin: 120, sbpMax: 140, spo2Min: 92, hrMax: 95 },
            debrief: "Acute pulmonary edema requires immediate high-dose IV Nitroglycerin to reduce venous return (preload) and systemic vascular resistance (afterload). Normal saline bolus would further drown the alveoli!"
        },
        {
            id: 12,
            title: "The Unstable Monomorphic Blitz",
            badge: "CASE #12 // ACLS RESUSCITATION",
            difficulty: "Attending Consultant",
            patient: {
                name: "Hannah W., Age 61",
                presentation: "Prior anterior MI patient experiencing severe presyncope, grey skin, diaphoresis. Telemetry shows wide, rapid, regular monomorphic saw-tooth QRS complexes at 185 bpm with a faint thready carotid pulse.",
                vitals: { hr: 185, sbp: 72, dbp: 40, spo2: 86, glucose: 104, rr: 24, temp: 36.7 },
                rhythm: "vtach",
                rhythmName: "Monomorphic Ventricular Tachycardia (Unstable with Pulse)",
                pupils: "Reactive (3mm)",
                lungs: "Clear",
                toxidrome: "Hemodynamically Unstable VT with Pulse"
            },
            correctDrugs: ["synchronized_cardioversion", "amiodarone"],
            lethalMistakes: ["adenosine", "labetalol", "defibrillation"],
            targetVitals: { sbpMin: 100, hrMin: 60, hrMax: 100 },
            debrief: "Unstable VT WITH a pulse requires Synchronized Cardioversion (timed to the R-wave to prevent R-on-T degeneration into V-Fib). Followed by antiarrhythmic infusion (Amiodarone) to suppress ectopy."
        },
        {
            id: 13,
            title: "The Post-Procedural Coma",
            badge: "CASE #13 // ANESTHESIOLOGY",
            difficulty: "Attending Consultant",
            patient: {
                name: "Liam O., Age 41",
                presentation: "Underwent outpatient colonoscopy. Received repeated doses of IV Midazolam. 45 minutes post-procedure, he remains completely unarousable with GCS 6 and bradypnea.",
                vitals: { hr: 56, sbp: 96, dbp: 62, spo2: 84, glucose: 90, rr: 6, temp: 36.4 },
                rhythm: "sinus_bradycardia",
                rhythmName: "Sinus Bradycardia with Hypoventilation",
                pupils: "Normal to sluggish (3mm)",
                lungs: "Clear, very shallow excursions",
                toxidrome: "Iatrogenic Benzodiazepine Over-sedation"
            },
            correctDrugs: ["flumazenil"],
            lethalMistakes: ["naloxone", "propofol", "fentanyl"],
            targetVitals: { spo2Min: 94, rrMin: 12, hrMin: 65 },
            debrief: "Flumazenil is a specific competitive antagonist at the benzodiazepine recognition site on the GABA-A receptor complex, reversing sedation and hypoventilation in procedural cases."
        },
        {
            id: 14,
            title: "The Acidotic Ketone Cascade",
            badge: "CASE #14 // ENDOCRINE CRITICAL CARE",
            difficulty: "Director of Emergency Medicine",
            patient: {
                name: "Zoe K., Age 19",
                presentation: "New-onset Type 1 Diabetes with 3 days of polyuria, Kussmaul rapid deep sighing respirations, fruity breath odor, and severe dehydration. Serum pH = 7.10, glucose = 540 mg/dL.",
                vitals: { hr: 134, sbp: 88, dbp: 50, spo2: 96, glucose: 540, rr: 32, temp: 37.4 },
                rhythm: "sinus_tachycardia",
                rhythmName: "Sinus Tachycardia (134 bpm) // DKA",
                pupils: "Dry mucous membranes, sunken eyes",
                lungs: "Deep Kussmaul hyperventilation",
                toxidrome: "Diabetic Ketoacidosis (High Anion Gap Metabolic Acidosis)"
            },
            correctDrugs: ["normal_saline", "insulin_regular"],
            lethalMistakes: ["dextrose_50", "labetalol", "propofol"],
            targetVitals: { sbpMin: 105, glucoseMin: 150, glucoseMax: 250, hrMax: 100 },
            debrief: "DKA management requires vigorous isotonic crystalloid volume expansion to restore tissue perfusion, alongside continuous regular insulin infusion to halt hepatic ketogenesis and drive glucose into cells."
        },
        {
            id: 15,
            title: "The Polytrauma Hemorrhagic Collapse",
            badge: "CASE #15 // TRAUMA RESUSCITATION",
            difficulty: "Director of Emergency Medicine",
            patient: {
                name: "Alexander R., Age 38",
                presentation: "High-speed motorcycle collision with open pelvic fracture and rigid distended abdomen. Pale, cold clammy extremities, barely palpable radial pulse.",
                vitals: { hr: 152, sbp: 60, dbp: 30, spo2: 88, glucose: 110, rr: 30, temp: 34.8 },
                rhythm: "sinus_tachycardia",
                rhythmName: "Severe Sinus Tachycardia // Class IV Hemorrhagic Shock",
                pupils: "Sluggish (4mm)",
                lungs: "Tachypneic",
                toxidrome: "Exsanguinating Hemorrhagic Shock & Lethal Triad"
            },
            correctDrugs: ["normal_saline", "norepinephrine", "calcium_gluconate"],
            lethalMistakes: ["propofol", "nitroglycerin", "labetalol", "adenosine"],
            targetVitals: { sbpMin: 90, hrMax: 115, spo2Min: 92 },
            debrief: "Class IV hemorrhagic shock requires massive volume replacement with crystalloids/blood products, vasopressor bridging (Norepinephrine) to maintain cerebral perfusion, and Calcium to counter citrate toxicity and restore cardiac inotropy."
        }
    ]
};
